# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20170810_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='finishedTime',
            new_name='finishedAt',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='startedTime',
            new_name='startedAt',
        ),
        migrations.AlterField(
            model_name='game',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='hltbUrl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='metacriticUrl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='modifiedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
