# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20170810_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='hltbUrl',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='metacriticUrl',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
