# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20170810_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='finishedAt',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
