# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20170825_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='releaseDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
