# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20170825_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='releaseDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
