# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_remove_game_platforms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gameTimes',
            new_name='gameLength',
        ),
    ]
