# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20170825_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gameLength',
            new_name='hltbLength',
        ),
    ]
