# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_game_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image',
        ),
    ]
