# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_game_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='user_id',
            new_name='user',
        ),
    ]
