# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_auto_20170929_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='hltbLength',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
