# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 08:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_auto_20180117_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='startedAt',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 1, 17, 8, 44, 18, 829380)),
        ),
    ]
