# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_auto_20180117_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='startedAt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
