# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_auto_20180117_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='startedAt',
            field=models.DateField(blank=True),
        ),
    ]
