# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_auto_20180117_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='finishedAt',
            new_name='stopped_playing_at',
        ),
    ]
