# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0038_game_beated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='beated',
            new_name='beaten',
        ),
    ]
