# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 00:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0043_auto_20180124_0000'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('user', 'name')]),
        ),
    ]
