# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0044_auto_20180124_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
