# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-08 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0047_replay'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Replay',
            new_name='Played',
        ),
    ]
