# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-08 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0048_auto_20200208_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='played',
            name='beaten',
            field=models.BooleanField(default=False),
        ),
    ]
